language: node_js

node_js: 
  - 10
  - 12
  - 14
  - 16
  - 18

branches:
  only:
    - master

matrix:
  allow_failures:
    - node_js: 7

install:
  - npm install

script:
  - npm test
  - npm build

notifications:
  email:
    on_success: never
    on_failure: always